/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MonitorPanel.java
 *
 * Created on 2009/02/02, 18:28:16
 */

/**
 *
 * @author tkurita
 */
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.Date;

public class MonitorPanel extends javax.swing.JPanel {
    private DspOutData dspOutData;

    void updateTimmings(float t1, float t2) {
       timmingField1.setText(Float.toString(t1));
       timmingField2.setText(Float.toString(t2));
    }

    public void setBSScaleMode(int mode) {
        bsScaleField.setSelectedIndex(mode);
    }

    public double getBSScale() {
        double result = 0.1;
        switch (bsScaleField.getSelectedIndex()) {
            case 0:
                result = 0.1; // 100 [pC/count]
                break;
            case 1:
                result = 0.001; //1 [pC/count]
                break;
            default:
                break;
        }
        return result;
    }

    public String getBSnAFieldText() {
        return bsnAField.getText();
    }

    public void setUpdateTimeField(long aValue) {
        Date d = new Date(aValue);
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        updateTimeField.setText(df.format(d));
    }
    
    public void setCurrentField1(double aValue) {
		currentField1.setText(Double.toString(aValue));
	}

	public void setCurrentField2(double aValue) {
		currentField2.setText(Double.toString(aValue));
	}

    public void setChargeField1(double aValue) {
		chargeField1.setText(Double.toString(aValue));
	}

    public void setChargeField2(double aValue) {
		chargeField2.setText(Double.toString(aValue));
    }

	public void setParticlesField1(double aValue) {
		particlesField1.setText(Double.toString(aValue));
	}

	public void setParticlesField2(double aValue) {
		particlesField2.setText(Double.toString(aValue));
	}

	public void setBSCountField(double aValue) {
		bsCountField.setText(Double.toString(aValue));
        double bsnC = aValue*getBSScale();
        bsnCField.setText(Double.toString(bsnC));
        double bsnA = bsnC/2;
        bsnAField.setText(Double.toString(bsnA));
	}

    public void setupData(DspOutData data) {
        dspOutData = data;
        setCurrentField1(dspOutData.getCurrent1());
        setCurrentField2(dspOutData.getCurrent2());
        setChargeField1(dspOutData.getCharge1());
        setChargeField2(dspOutData.getCharge2());
        setParticlesField1(dspOutData.getParticles1());
        setParticlesField2(dspOutData.getParticles2());
        setBSCountField(dspOutData.getBSCount());
        setUpdateTimeField(dspOutData.getUpdatedTime());
    }

    public boolean setupDataWithFile(File dspoutFile) {
        DspOutData data = new DspOutData();
        boolean result = data.readData(dspoutFile);
        if (result) {
            setupData(data);
        }
        return result;
    }

    public DspOutData getDspOutData() {
        return dspOutData;
    }
    public boolean hasValues() {
        return (dspOutData != null);
    }

    /** Creates new form MonitorPanel */
    public MonitorPanel() {
        initComponents();
        dspOutData = null;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timmingField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        updateTimeField = new javax.swing.JTextField();
        currentField1 = new javax.swing.JTextField();
        chargeField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        particlesField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        particlesField2 = new javax.swing.JTextField();
        chargeField2 = new javax.swing.JTextField();
        currentField2 = new javax.swing.JTextField();
        timmingField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        bsCountField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        bsnCField = new javax.swing.JTextField();
        bsnAField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        bsScaleField = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        accEfficiencyField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        extractEfficiencyField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();

        setFont(new java.awt.Font("MS UI Gothic", 0, 18));
        setPreferredSize(new java.awt.Dimension(600, 196));

        timmingField1.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        timmingField1.setText("timmingField1");
        timmingField1.setMaximumSize(new java.awt.Dimension(120, 25));
        timmingField1.setMinimumSize(new java.awt.Dimension(100, 25));
        timmingField1.setPreferredSize(new java.awt.Dimension(120, 25));

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 0, 18));
        jLabel1.setText("更新時間 :");

        jLabel2.setFont(new java.awt.Font("MS UI Gothic", 0, 18));
        jLabel2.setText("電流 [mA] :");

        updateTimeField.setFont(new java.awt.Font("MS UI Gothic", 0, 18));
        updateTimeField.setText("lastupDateField");

        currentField1.setFont(new java.awt.Font("MS UI Gothic", 0, 18));
        currentField1.setText("currentField1");
        currentField1.setMaximumSize(new java.awt.Dimension(9, 1));
        currentField1.setPreferredSize(new java.awt.Dimension(120, 25));
        currentField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentField1ActionPerformed(evt);
            }
        });

        chargeField1.setFont(new java.awt.Font("MS UI Gothic", 0, 18));
        chargeField1.setText("chargeField1");
        chargeField1.setMaximumSize(new java.awt.Dimension(120, 25));
        chargeField1.setPreferredSize(new java.awt.Dimension(120, 25));
        chargeField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chargeField1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("MS UI Gothic", 0, 18));
        jLabel3.setText("タイミング1 :");

        jLabel4.setFont(new java.awt.Font("MS UI Gothic", 0, 18));
        jLabel4.setText("電荷量 [nC] :");

        jLabel5.setFont(new java.awt.Font("MS UI Gothic", 0, 18));
        jLabel5.setText("粒子数 :");

        particlesField1.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        particlesField1.setText("particlesField1");
        particlesField1.setMaximumSize(new java.awt.Dimension(120, 25));
        particlesField1.setPreferredSize(new java.awt.Dimension(120, 25));

        jLabel6.setFont(new java.awt.Font("MS UI Gothic", 0, 18));
        jLabel6.setText("タイミング1 :");

        jLabel7.setFont(new java.awt.Font("MS UI Gothic", 0, 18));
        jLabel7.setText("電流 [mA] :");

        jLabel8.setFont(new java.awt.Font("MS UI Gothic", 0, 18));
        jLabel8.setText("電荷量 [nC] :");

        jLabel9.setFont(new java.awt.Font("MS UI Gothic", 0, 18));
        jLabel9.setText("粒子数 :");

        particlesField2.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        particlesField2.setText("particleField1");

        chargeField2.setFont(new java.awt.Font("MS UI Gothic", 0, 18));
        chargeField2.setText("chargeField1");
        chargeField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chargeField2ActionPerformed(evt);
            }
        });

        currentField2.setFont(new java.awt.Font("MS UI Gothic", 0, 18));
        currentField2.setText("currentField1");
        currentField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentField2ActionPerformed(evt);
            }
        });

        timmingField2.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        timmingField2.setText("timmingField2");
        timmingField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timmingField2ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("MS UI Gothic", 0, 18));
        jLabel10.setText("BS");

        bsCountField.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        bsCountField.setText("bsCount");

        jLabel11.setFont(new java.awt.Font("MS UI Gothic", 0, 18));
        jLabel11.setText("[nC]");

        bsnCField.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        bsnCField.setText("bsnC");

        bsnAField.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        bsnAField.setText("bsnA");

        jLabel12.setFont(new java.awt.Font("MS UI Gothic", 0, 18));
        jLabel12.setText("[nA]");

        bsScaleField.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        bsScaleField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "100 [pC/count]", "1 [pC/count]" }));
        bsScaleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsScaleFieldActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("MS UI Gothic", 0, 18));
        jLabel13.setText("加速効率 :");

        jLabel14.setFont(new java.awt.Font("MS UI Gothic", 0, 18));
        jLabel14.setText("出射効率 :");

        accEfficiencyField.setFont(new java.awt.Font("MS UI Gothic", 0, 18));
        accEfficiencyField.setText("accEfficiencyFeild");

        jLabel15.setFont(new java.awt.Font("MS UI Gothic", 0, 18));
        jLabel15.setText("[%]");

        extractEfficiencyField.setFont(new java.awt.Font("MS UI Gothic", 0, 18));
        extractEfficiencyField.setText("extractEfficiencyFeild");
        extractEfficiencyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extractEfficiencyFieldActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("MS UI Gothic", 0, 18));
        jLabel16.setText("[%]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(particlesField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chargeField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timmingField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(currentField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(particlesField2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chargeField2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(currentField2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timmingField2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bsScaleField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bsnAField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12))
                            .addComponent(bsCountField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bsnCField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accEfficiencyField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(extractEfficiencyField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(updateTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(timmingField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(currentField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(chargeField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(timmingField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(currentField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(chargeField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(particlesField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(particlesField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(60, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(bsScaleField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bsCountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bsnCField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bsnAField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(37, 37, 37)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(accEfficiencyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(extractEfficiencyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void currentField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentField1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_currentField1ActionPerformed

    private void chargeField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chargeField1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_chargeField1ActionPerformed

    private void chargeField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chargeField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chargeField2ActionPerformed

    private void currentField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentField2ActionPerformed

    private void bsScaleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsScaleFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_bsScaleFieldActionPerformed

    private void extractEfficiencyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extractEfficiencyFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_extractEfficiencyFieldActionPerformed

    private void timmingField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timmingField2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_timmingField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accEfficiencyField;
    private javax.swing.JTextField bsCountField;
    private javax.swing.JComboBox bsScaleField;
    private javax.swing.JTextField bsnAField;
    private javax.swing.JTextField bsnCField;
    private javax.swing.JTextField chargeField1;
    private javax.swing.JTextField chargeField2;
    private javax.swing.JTextField currentField1;
    private javax.swing.JTextField currentField2;
    private javax.swing.JTextField extractEfficiencyField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField particlesField1;
    private javax.swing.JTextField particlesField2;
    private javax.swing.JTextField timmingField1;
    private javax.swing.JTextField timmingField2;
    private javax.swing.JTextField updateTimeField;
    // End of variables declaration//GEN-END:variables

}
