/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MonitorWindowUI.java
 *
 * Created on 2009/02/02, 17:03:35
 */

/**
 *
 * @author tkurita
 */

import java.io.*;
import java.awt.*;
import java.util.Timer;
import java.util.TimerTask;
        
public class MonitorWindowUI extends javax.swing.JFrame {
    private Color panelDefaultBackground;
    private SettingWindow settingWindow;
    private Timer timer;
    private File dspoutFile;

    class DSPOutWatcher extends TimerTask {
        long lastUpdatedData = 0;
        public void run() {
            if (dspoutFile.isFile()) {
                long data = dspoutFile.lastModified();
                if (data < lastUpdatedData) {
               		return;
                }
                lastUpdatedData = data;
            } else {
                return;
            }
            if (extractionButton.isSelected()) {
                extractionPanel.readData(dspoutFile);
            } else {
                leakPanel.readData(dspoutFile);
            }
        }
	}

    private void setupTimerTask() {
		timer = new Timer(true);
		timer.schedule(new DSPOutWatcher(), 0, 1000);
	}

    public void updateTimmings(float t1, float t2) {
        extractionPanel.updateTimmings(t1, t2);
        leakPanel.updateTimmings(t1, t2);
    }
    /** Creates new form MonitorWindowUI */
    public MonitorWindowUI() {
        initComponents();
        settingWindow = SettingWindow.getInstance(this);
        settingWindow.setVisible(true);


        panelDefaultBackground = extractionPanel.getBackground();
        extractionButton.doClick();
        dspoutFile = new File("dspout.txt");
        extractionPanel.readData(dspoutFile);
        leakPanel.setBSScaleMode(1);
        setupTimerTask();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modeButtonGroup = new javax.swing.ButtonGroup();
        extractionButton = new javax.swing.JToggleButton();
        leakButton = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        extCurrentField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        leakCurrentField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        leakPanel = new MonitorPanel();
        extractionPanel = new MonitorPanel();
        swapButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        modeButtonGroup.add(extractionButton);
        extractionButton.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        extractionButton.setText("出射");
        extractionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extractionButtonActionPerformed(evt);
            }
        });

        modeButtonGroup.add(leakButton);
        leakButton.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        leakButton.setText("漏れ");
        leakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leakButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel1.setText("出射電流");

        extCurrentField.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        extCurrentField.setText("extCurrentField");

        jLabel2.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel2.setText("[nA]");

        jLabel3.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel3.setText("漏れ");

        leakCurrentField.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        leakCurrentField.setText("leakCurrentField");

        jLabel4.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel4.setText("[%]");

        leakPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        extractionPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        swapButton.setText("入れ替え↑↓");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(extCurrentField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(leakCurrentField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(extractionPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
                            .addComponent(leakPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(leakButton)
                                        .addGap(564, 564, 564)
                                        .addComponent(swapButton))
                                    .addComponent(extractionButton))
                                .addGap(63, 63, 63)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(extractionButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(extractionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(leakButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(swapButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(leakPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(extCurrentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(leakCurrentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void extractionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extractionButtonActionPerformed
        // TODO add your handling code here:
        extractionPanel.setBackground(panelDefaultBackground);
        leakPanel.setBackground(Color.gray);
    }//GEN-LAST:event_extractionButtonActionPerformed

    private void leakButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leakButtonActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        leakPanel.setBackground(panelDefaultBackground);
        extractionPanel.setBackground(Color.gray);
    }//GEN-LAST:event_leakButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonitorWindowUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField extCurrentField;
    private javax.swing.JToggleButton extractionButton;
    private MonitorPanel extractionPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JToggleButton leakButton;
    private javax.swing.JTextField leakCurrentField;
    private MonitorPanel leakPanel;
    private javax.swing.ButtonGroup modeButtonGroup;
    private javax.swing.JButton swapButton;
    // End of variables declaration//GEN-END:variables

}
